-- Character-specific KOF98UM input commands derived from the supplied command guide.
-- Charge, airborne-only, and multi-tap inputs are omitted until their states are modeled.
local commandSets = {
  ["Benimaru"] = {
    { name = "Jackknife Kick", motion = {"forward"}, buttons = {32} },
    { name = "Raijin Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Shinkuu Katategoma", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Benimaru Corridor", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Iai Geri", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Handou Sandan Geri", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Super Inazuma Kick", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Raikou Ken", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Electrigger", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
    { name = "Raikou Katategoma", motion = {"down", "downback", "back", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Daimon"] = {
    { name = "Tama Tsubushi", motion = {"forward"}, buttons = {16} },
    { name = "Zujou Barai", motion = {"downforward"}, buttons = {64} },
    { name = "Kumo Tsukami Nage", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16} },
    { name = "Kirikabu Gaeshi", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {64} },
    { name = "Jirai Shin", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Chou Oosotogari", motion = {"forward", "down", "downforward"}, buttons = {32, 128}, close = true },
    { name = "Nekko Gaeshi", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Tenchi Gaeshi", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Ura Nage", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {32, 128} },
    { name = "Chou Ukemi", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Jigoku Gokuraku Otoshi", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
    { name = "Arashi no Yama: Nekko Nuki", motion = {"back", "downback", "down", "downforward", "forward", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128}, next = {"Bukko Nuki Ura Nage", "Zoku: Tenchi Gaeshi"}, close = true },
    { name = "Bukko Nuki Ura Nage", motion = {"forward", "down", "downforward"}, buttons = {32, 128}, followupOnly = true },
    { name = "Zoku: Tenchi Gaeshi", motion = {"forward", "down", "downforward"}, buttons = {32, 128}, followupOnly = true },
  },
  ["Terry"] = {
    { name = "Back Knuckle", motion = {"forward"}, buttons = {16} },
    { name = "Rising Upper", motion = {"downforward"}, buttons = {64} },
    { name = "Power Wave", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Burning Knuckle", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Crack Shoot", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Rising Tackle", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Power Dunk", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Power Charge", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Power Geyser", motion = {"down", "downback", "back", "downback", "forward"}, buttons = {16, 64} },
    { name = "High Angle Geyser", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Andy"] = {
    { name = "Age Men", motion = {"downforward"}, buttons = {16} },
    { name = "Uwa Agito", motion = {"forward"}, buttons = {32} },
    { name = "Hishou Ken", motion = {"down", "downback", "back"}, buttons = {16} },
    { name = "Geki Hishou Ken", motion = {"down", "downback", "back"}, buttons = {64} },
    { name = "Gekiheki Haisui Shou", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64}, close = true },
    { name = "Kuuha Dan", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Shouryuu Dan", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Zen'ei Ken", motion = {"downback", "forward"}, buttons = {16, 64} },
    { name = "Hishou Ryuusei Ken", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Chou Reppa Dan", motion = {"down", "downback", "back", "downback", "forward"}, buttons = {32, 128} },
  },
  ["Joe"] = {
    { name = "Low Kick", motion = {"forward"}, buttons = {32} },
    { name = "Sliding", motion = {"downforward"}, buttons = {32} },
    { name = "Bakuretsu Finish (high)", motion = {"down", "downforward", "forward"}, buttons = {16, 64}, followupOnly = true },
    { name = "Bakuretsu Finish (low)", motion = {"down", "downforward", "forward"}, buttons = {32, 128}, followupOnly = true },
    { name = "Hurricane Upper", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Tiger Kick", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Ougon no Kakato", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Slash Kick", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Explosive Hurricane Tiger Heel", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Screw Upper", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Ryo"] = {
    { name = "Hyouchuu Wari", motion = {"forward"}, buttons = {16} },
    { name = "Ko'oh Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Kohou", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Moh Koh Raijin Satsu", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Hien Shippuu Kyaku", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Kyokugen-ryuu Renbu Ken", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64}, close = true },
    { name = "Haoh Shokou Ken", motion = {"forward", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuko Ranbu", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Tenchi Haoh Ken", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Robert"] = {
    { name = "Kouryuu Koukyaku Geri", motion = {"forward"}, buttons = {16} },
    { name = "Ryuu Hanshuu", motion = {"forward"}, buttons = {32} },
    { name = "Ryuu-Geki Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuuga", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Ryuu Zanshou", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Kyokugen-ryuu Renbu Kyaku", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128}, close = true },
    { name = "Hien Senpuu Kyaku", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Haoh Shokou Ken", motion = {"forward", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuko Ranbu", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
  },
  ["Yuri"] = {
    { name = "En Yoku", motion = {"forward"}, buttons = {32} },
    { name = "Ko'oh Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Yuri Chou Upper (Kuuga)", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Yuri Chou Knuckle", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Yuri Chou Mawashi Geri", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Haoh Shokou Ken", motion = {"forward", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Hien Rekkou", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Hien Hou'ou Kyaku", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Leona"] = {
    { name = "Strike Arch", motion = {"forward"}, buttons = {32} },
    { name = "I-Slasher", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Earring Explosive", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Gravity Storm", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Rebel Spark", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Ralf"] = {
    { name = "Super Argentine Backbreaker", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128}, close = true },
    { name = "Galactica Phantom", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Baribari Vulcan Punch", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Umanori Vulcan Punch", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Clark"] = {
    { name = "Stomping", motion = {"forward"}, buttons = {32} },
    { name = "Super Arabian Burglary Backbreaker *", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16} },
    { name = "Rolling Cradle *", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {64} },
    { name = "Super Argentine Backbreaker *", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128}, close = true },
    { name = "Napalm Stretch *", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Frankensteiner *", motion = {"forward", "down", "downforward"}, buttons = {32, 128}, close = true },
    { name = "Ultra Argentine Backbreaker", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
    { name = "Running Three", motion = {"back", "downback", "down", "downforward", "forward", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Napalm Strike", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Athena"] = {
    { name = "Renkantai", motion = {"forward"}, buttons = {32} },
    { name = "Psycho Ball", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Psycho Reflector", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Psychic Teleport", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Super Psychic Throw", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64}, close = true },
    { name = "Psycho Ball Revolution", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Kensou"] = {
    { name = "Kobokushu", motion = {"forward"}, buttons = {16} },
    { name = "Kousentai", motion = {"forward"}, buttons = {32} },
    { name = "Cho Kyuudan", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Ryuu Renga: Chiryuu", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16} },
    { name = "Ryuu Renga: Tenryuu", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {64} },
    { name = "Ryuu Renda", motion = {"forward", "down", "downforward"}, buttons = {16, 64}, close = true },
    { name = "Nikku Man o Kuu", motion = {"down", "downback", "back", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Senki Hakkei", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64}, close = true },
    { name = "Shinryuu Seioh Rekkyaku", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {32} },
    { name = "Shinryuu Tenbu Kyaku", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {128} },
  },
  ["Chin"] = {
    { name = "Suiho Hyotan Geki", motion = {"forward"}, buttons = {16} },
    { name = "Kisui Shuu", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Hyotan Geki", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Ryuurin Hourai", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Kaiten-teki Kuutotsu Ken", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Suikan Kanou", motion = {"down", "down"}, buttons = {16, 64}, next = {"Choushuu Rikugyo", "Kaiten-teki Kuutotsu Ken"} },
    { name = "Choushuu Rikugyo", motion = {"forward"}, buttons = {16, 64}, followupOnly = true },
    { name = "Kaiten-teki Kuutotsu Ken", motion = {"forward"}, buttons = {32, 128}, followupOnly = true },
    { name = "Bogetsu Sui", motion = {"down", "down"}, buttons = {32, 128}, next = {"Ryuda Hanyo", "Rigyo Hanyo", "Kaiten-teki Kuutotsu Ken"} },
    { name = "Ryuda Hanyo", motion = {"up"}, buttons = {32}, followupOnly = true },
    { name = "Rigyo Hanyo", motion = {"up"}, buttons = {128}, followupOnly = true },
    { name = "Kaiten-teki Kuutotsu Ken", motion = {"forward"}, buttons = {32, 128}, followupOnly = true },
    { name = "Goen Shorai", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Goen Enpo", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Daikyuu Inshuu", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
    { name = "Sentori Suiho", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Chizuru"] = {
    { name = "Jokatsu: Sousou (Zheng Zheng)", motion = {"forward"}, buttons = {16} },
    { name = "Jokatsu: Sousou (Cang Cang)", motion = {"forward"}, buttons = {32} },
    { name = "Jokatsu: Sousou (Cong Cong)", motion = {"downforward"}, buttons = {128} },
    { name = "108 Katsu: Tamayura no Shitsune", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "100 Katsu: Tenjin no Kotowari", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Rimen 85 Katsu: Reigi no Ishizue", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Rimen 1 Katsu: Sanrai no Fujin", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Mai"] = {
    { name = "Koku'en no Mai", motion = {"forward"}, buttons = {32} },
    { name = "Benitsuru no Mai", motion = {"downforward"}, buttons = {32} },
    { name = "Kacho Sen", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuu Enbu", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Hakuro no Mai", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Hissatsu Shinobi Bachi", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Hishou Ryuu'en Jin", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Mizudori no Mai", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Chou Hissatsu Shinobi Bachi", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["King"] = {
    { name = "Sliding Kick", motion = {"downforward"}, buttons = {128} },
    { name = "Venom Strike", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Double Strike", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Mirage Kick", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Tornado Kick", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Surprise Rose", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Trap Shot", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Illusion Dance", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Silent Flash", motion = {"down", "downback", "back", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Kim"] = {
    { name = "Dora Yup Chagi", motion = {"forward"}, buttons = {16} },
    { name = "Neri Chagi", motion = {"forward"}, buttons = {32} },
    { name = "Haki Kyaku", motion = {"down", "down"}, buttons = {32, 128} },
    { name = "Hangetsu Zan", motion = {"down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Chang"] = {
    { name = "Hiki Nige", motion = {"downforward"}, buttons = {16} },
    { name = "Dai Hakai Nage", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Tekkyuu Dai Bousou", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Tekkyuu Dai Assatsu", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Choi"] = {
    { name = "Nidan Zan", motion = {"forward"}, buttons = {16} },
    { name = "Toorima Geri", motion = {"forward"}, buttons = {32} },
    { name = "Kaiten Hien Zan", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Hou'ou Kyaku", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Yashiro"] = {
    { name = "Regret Bash", motion = {"forward"}, buttons = {16} },
    { name = "Step Side Kick", motion = {"forward"}, buttons = {32} },
    { name = "Upper Duel", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Jet Counter", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Mighty Missile Bash", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Sledgehammer", motion = {"down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Chris"] = {
    { name = "Spinning Array", motion = {"forward"}, buttons = {16} },
    { name = "Reverse Anchor Kick", motion = {"forward"}, buttons = {32} },
    { name = "Carry Off Kick", motion = {"downforward"}, buttons = {32} },
    { name = "Slide Touch", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Scramble Dash", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Shooting Dancer Thrust", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Shooting Dancer Step", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Direction Change", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Hunting Air Blast", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Chain Slide Touch", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Twister Drive", motion = {"down", "downback", "back", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Yamazaki"] = {
    { name = "Bussashi", motion = {"forward"}, buttons = {16} },
    { name = "Sabaki no Aikuchi", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Yakiire", motion = {"forward", "down", "downforward"}, buttons = {32} },
    { name = "Sunakake", motion = {"forward", "down", "downforward"}, buttons = {128} },
    { name = "Bakudan Pachiki", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Bai Gaeshi", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Sadomazo", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Drill", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
  },
  ["Blue Mary"] = {
    { name = "Hammer arch", motion = {"forward"}, buttons = {16} },
    { name = "Double Rolling", motion = {"forward"}, buttons = {32} },
    { name = "Climbing Arrow", motion = {"downforward"}, buttons = {32} },
    { name = "M. Spider", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Real Backdrop", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Spin Fall", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "M. Reverse Facelock", motion = {"down", "downback", "back"}, buttons = {32} },
    { name = "M. Head Buster", motion = {"down", "downback", "back"}, buttons = {128} },
    { name = "Vertical Arrow", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "M. Splash Rose", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "M. Dynamite Swing", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "M. Typhoon", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128}, close = true },
  },
  ["Billy"] = {
    { name = "Dai Kaiten Geri", motion = {"forward"}, buttons = {16} },
    { name = "Boutaka Tobigeri", motion = {"forward"}, buttons = {32} },
    { name = "Sansetsu Kon: Chuudan Uchi", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Sen'en Sakkon", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Karyuu Tsuigeki Kon", motion = {"down", "downback", "back"}, buttons = {32} },
    { name = "Suiryuu Tsuigeki Kon", motion = {"down", "downback", "back"}, buttons = {128} },
    { name = "Chou Kaen Senpuu Kon", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Dai Senpuu", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Iori"] = {
    { name = "Geshiki: Goufu In \"Shinigame\"", motion = {"forward"}, buttons = {32} },
    { name = "108 Shiki: Yami Barai", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "100 Shiki: Oniyaki", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "311 Shiki: Tsumagushi", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "212 Shiki: Kototsuki In", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Kuzukaze", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Kin 1211 Shiki: Ya Otome", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Ura 108 Shiki: Ya Sakazuki", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Mature"] = {
    { name = "Sacrilege", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Despair", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Metal Massacre", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Deicide", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Ebony Tears", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Nocturnal Lights", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Heaven's Gate", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Vice"] = {
    { name = "Monstrosity", motion = {"forward"}, buttons = {16} },
    { name = "Blackend", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64}, close = true },
    { name = "Deicide", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Mayhem", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Outrage", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Gore Fest", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Withering Surface", motion = {"back", "downback", "down", "downforward", "forward", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Negative Gain", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128}, close = true },
    { name = "Dying Fetus", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Heidern"] = {
    { name = "Steiner's Knuckles", motion = {"forward"}, buttons = {32} },
    { name = "Storm Bringer", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
    { name = "Kill Bringer", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Final Bringer", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Heidern End", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Takuma"] = {
    { name = "Oni Guruma", motion = {"forward"}, buttons = {16} },
    { name = "Kawara Wari", motion = {"forward"}, buttons = {32} },
    { name = "Ko'oh Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Zanretsu Ken", motion = {"forward", "back", "forward"}, buttons = {16, 64} },
    { name = "Moh Koh Burai Gan", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Shoran Kyaku", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Shin Kishin Geki", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64}, close = true },
    { name = "Haoh Shikou Ken", motion = {"forward", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuuko Ranbu", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
  },
  ["Saisyu"] = {
    { name = "Ge Shiki: Gou Tsui", motion = {"forward"}, buttons = {16} },
    { name = "Ge Shiki: Kubu Tsuchi", motion = {"forward"}, buttons = {32} },
    { name = "108 Shiki: Yami Barai", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "100 Shiki: Oniyaki", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "110 Shiki: Nataguruma", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Kamukakari", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "1127 Shiki: Tsumugari", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Heavy D!"] = {
    { name = "Rock Crush", motion = {"forward"}, buttons = {16} },
    { name = "R.S.D. (Rolling Soul Diver)", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Dancing Beat", motion = {"forward", "down", "downforward"}, buttons = {16, 64}, close = true },
    { name = "Blast Upper", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Soul Flower", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Shadow", motion = {"down", "down"}, buttons = {16, 64} },
    { name = "D. Crazy", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "D. Shadow", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Lucky"] = {
    { name = "Lucky Kick", motion = {"forward"}, buttons = {32} },
    { name = "Death Bound", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Death Shoot", motion = {"down", "down"}, buttons = {16, 32, 64, 128} },
    { name = "Lucky Vision", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Cyclone Break", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Death Heel", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Hell Bound", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Lucky Driver", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128}, close = true },
  },
  ["Brian"] = {
    { name = "Brian Tornado", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Hyper Tackle", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Rocket Tackle", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Brian Hammer", motion = {"down", "downback", "back"}, buttons = {16, 64}, next = {"Samurai Bomb", "Shoulder Backbreaker"} },
    { name = "Samurai Bomb", motion = {"down", "down"}, buttons = {16, 64}, followupOnly = true },
    { name = "Shoulder Backbreaker", motion = {"down", "down", "down"}, buttons = {32, 128}, followupOnly = true },
    { name = "American Supernova", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Galaxy Cyclone", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Big Bang Tackle", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Geese"] = {
    { name = "Raikou Mawashi Geri", motion = {"forward"}, buttons = {32} },
    { name = "Reppuu Ken", motion = {"down", "downforward", "forward"}, buttons = {16} },
    { name = "Double Reppuu Ken", motion = {"down", "downforward", "forward"}, buttons = {64} },
    { name = "Jaei Ken", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Hishou Nichirin Zan", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Joudan Atemi Nage", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32} },
    { name = "Chuudan Atemi Nage", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {128} },
    { name = "Gedan Atemi Nage", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32} },
    { name = "Shinkuu Nage", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Rising Storm", motion = {"downback", "forward", "downforward", "down", "downback", "back", "downforward"}, buttons = {16, 64} },
    { name = "Deadly Rave", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
  },
  ["Krauser"] = {
    { name = "Leg Tomahawk", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Kaiser Kick", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Phoenix Throw", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Kaiser Suplex", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Lift Up Blow", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {32, 128}, close = true },
    { name = "Unlimited Desire", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Gigantic Cyclone", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
  },
  ["Mr. Big"] = {
    { name = "Prick Stick", motion = {"forward"}, buttons = {16} },
    { name = "Ground Blaster", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Californian Romance", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Cross Diving", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Spinning Lancer", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Drum Shot", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64} },
    { name = "Blaster Wave", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Raging Spear", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
  },
  ["Yashiro (Orochi)"] = {
    { name = "Saku", motion = {"forward"}, buttons = {16} },
    { name = "Bu", motion = {"forward"}, buttons = {32} },
    { name = "Kujiku Daichi", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Niragu Daichi", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64}, close = true },
    { name = "Odoru Daichi", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Ankoku Jigoku Gokuraku Otoshi", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
    { name = "Araburu Daichi", motion = {"back", "downback", "down", "downforward", "forward", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Shermie (Orochi)"] = {
    { name = "Kourai", motion = {"forward"}, buttons = {32} },
    { name = "Mugetsu no Raiun", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 32, 64, 128} },
    { name = "Yatanagi no Muchi", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Shajitsu no Odori", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Ankoku Raikou Ken", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Shukumei, Gen'ei, Shinshi", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Chris (Orochi)"] = {
    { name = "Muyou no Ono", motion = {"forward"}, buttons = {16} },
    { name = "Jukei no Oni", motion = {"forward"}, buttons = {32} },
    { name = "Setsudan no Koto", motion = {"downforward"}, buttons = {32} },
    { name = "Taiyou wo Iru Honoo", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Kagami wo Hofuru Honoo", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Tsuki wo Tsumu Honoo", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Shishi wo Kamu Honoo", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128}, close = true },
    { name = "Daichi o Harau Gouka", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Eiji"] = {
    { name = "Kikou Hau", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Kasumi Kiri", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Ryuu Kagejin", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Kage Utsushi", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Kotsu Hazaki Kiri", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Zantetsu Nami", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Zantetsu Kamakiriken", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Kasumi"] = {
    { name = "Hiji Ate", motion = {"forward"}, buttons = {16} },
    { name = "Taikuu Kasane Ate", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Tatsumaki Souda", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {16, 64}, close = true },
    { name = "Futa Tanagokurodan", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Ikazuchi Houkou", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Messhin Mutou", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32} },
    { name = "Sasshou Inshuu", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {128} },
    { name = "Hakuzan Tou", motion = {"down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Shingo"] = {
    { name = "Geshiki: Goufu \"Kakkodake\"", motion = {"forward"}, buttons = {32} },
    { name = "114 Shiki: Aragami Mikansei", motion = {"down", "downforward", "forward"}, buttons = {16} },
    { name = "115 Shiki: Dokugami Mikansei", motion = {"down", "downforward", "forward"}, buttons = {64} },
    { name = "100 Shiki: Oniyaki Mikansei", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Shingo Kinsei Oreshiki: Nie Togi", motion = {"forward", "down", "downforward"}, buttons = {32, 128}, close = true },
    { name = "Shingo Kick", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "101 Shiki: Oboro Guruma Mikansei", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Shingo Kinsei Oreshiki: Tsuki Hiji", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Kake Hourin", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Burning Shingo", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Rugal"] = {
    { name = "Double Tomahawk", motion = {"forward"}, buttons = {32} },
    { name = "Reppuu Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "God Press", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Dark Barrier", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Genocide Cutter", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Gigantic Pressure", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Dead End Screamer", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Kyo (EX)"] = {
    { name = "Geshiki: Goufu You", motion = {"forward"}, buttons = {32} },
    { name = "88 Shiki", motion = {"downforward"}, buttons = {128} },
    { name = "108 Shiki: Yami Barai", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "100 Shiki: Oniyaki", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "212 Shiki: Kototsuki You", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Terry (EX)"] = {
    { name = "Back Knuckle", motion = {"forward"}, buttons = {16} },
    { name = "Rising Upper", motion = {"downforward"}, buttons = {64} },
    { name = "Power Wave", motion = {"down", "downforward", "forward"}, buttons = {16} },
    { name = "Round Wave", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Burning Knuckle", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Crack Shoot", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Fire Kick", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Power Geyser", motion = {"down", "downback", "back", "downback", "forward"}, buttons = {16, 64} },
  },
  ["Andy (EX)"] = {
    { name = "Age Men", motion = {"downforward"}, buttons = {16} },
    { name = "Uwa Agito", motion = {"forward"}, buttons = {32} },
    { name = "Hishou Ken", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Kuuha Dan", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Shouryuu Dan", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Zen'ei Ken", motion = {"downback", "forward"}, buttons = {16, 64} },
    { name = "Bakushin", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Chou Reppa Dan", motion = {"down", "downback", "back", "downback", "forward"}, buttons = {32, 128} },
  },
  ["Joe (EX)"] = {
    { name = "Low Kick", motion = {"forward"}, buttons = {32} },
    { name = "Sliding", motion = {"downforward"}, buttons = {32} },
    { name = "Hurricane Upper", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Tiger Kick", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Ougon no Kakato", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Slash Kick", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Pressure Knee", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Screw Upper", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Thunder Fire", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Ryo (EX)"] = {
    { name = "Hyouchuu Wari", motion = {"forward"}, buttons = {16} },
    { name = "Ko'oh Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Kohou", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Zanretsu Ken", motion = {"forward", "back", "forward"}, buttons = {16, 64} },
    { name = "Hien Shippuu Kyaku", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Haoh Shokou Ken", motion = {"forward", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuko Ranbu", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
  },
  ["Robert (EX)"] = {
    { name = "Kouryuu Koukyaku Geri", motion = {"forward"}, buttons = {16} },
    { name = "Ryuu Hanshuu", motion = {"back"}, buttons = {32} },
    { name = "Ryuu Hanshuu", motion = {"forward"}, buttons = {32} },
    { name = "Ryuu-Geki Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuuga", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Hien Senpuu Kyaku", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Gen'ei Kyaku", motion = {"forward", "back", "forward"}, buttons = {32, 128} },
    { name = "Haoh Shokou Ken", motion = {"forward", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuko Ranbu", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
  },
  ["Yuri (EX)"] = {
    { name = "En Yoku", motion = {"forward"}, buttons = {32} },
    { name = "Ko'oh Ken", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Saifa", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Hyakuretsu Binta", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Haoh Shokou Ken", motion = {"forward", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Shin! Chou Upper", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Hien Hou'ou Kyaku", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
  },
  ["Mai (EX)"] = {
    { name = "Koku'en no Mai", motion = {"forward"}, buttons = {32} },
    { name = "Benitsuru no Mai", motion = {"downforward"}, buttons = {32} },
    { name = "Kacho Sen", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Ryuu Enbu", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Hissatsu Shinobi Bachi", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Sayo Chidori", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Chou Hissatsu Shinobi Bachi", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["King (EX)"] = {
    { name = "Sliding Kick", motion = {"downforward"}, buttons = {128} },
    { name = "Venom Strike", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Tornado Kick", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Trap Shot", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Surprise Rose", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Double Strike", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Yamazaki (EX)"] = {
    { name = "Bussashi", motion = {"forward"}, buttons = {16} },
    { name = "Sabaki no Aikuchi", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "Yakiire", motion = {"forward", "down", "downforward"}, buttons = {32} },
    { name = "Bai Gaeshi", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Sadomazo", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Drill", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
  },
  ["Blue Mary (EX)"] = {
    { name = "Hammer arch", motion = {"forward"}, buttons = {16} },
    { name = "Double Rolling", motion = {"forward"}, buttons = {32} },
    { name = "Climbing Arrow", motion = {"downforward"}, buttons = {32} },
    { name = "Real Counter", motion = {"down", "downback", "back"}, buttons = {16, 64}, next = {"Backdrop *", "Facelock *"} },
    { name = "Backdrop *", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64}, close = true, followupOnly = true },
    { name = "Facelock *", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {32, 128}, close = true, followupOnly = true },
    { name = "Vertical Arrow", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "M. Driving Smasher", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {32, 128}, close = true },
    { name = "M. Escalation", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64}, next = {"Spin Fall"} },
    { name = "Spin Fall", motion = {"down", "downforward", "forward"}, buttons = {32, 128}, followupOnly = true },
  },
  ["Billy (EX)"] = {
    { name = "Dai Kaiten Geri", motion = {"forward"}, buttons = {16} },
    { name = "Boutaka Tobigeri", motion = {"forward"}, buttons = {32} },
    { name = "Sansetsu Kon: Chuudan Uchi", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Suzume Otoshi", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Karyuu Tsuigeki Kon", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Chou Kaen Senpuu Kon", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Salamander Stream", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Kuren Satsu Kon", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Geese (EX)"] = {
    { name = "Raikou Mawashi Geri", motion = {"forward"}, buttons = {32} },
    { name = "Reppuu Ken", motion = {"down", "downforward", "forward"}, buttons = {16} },
    { name = "Double Reppuu Ken", motion = {"down", "downforward", "forward"}, buttons = {64} },
    { name = "Jaei Ken", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Joudan Atemi Nage", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32} },
    { name = "Chuudan Atemi Uchi", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {128} },
    { name = "Shinkuu Nage", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {64}, close = true },
    { name = "Rising Storm", motion = {"downback", "forward", "downforward", "down", "downback", "back", "downforward"}, buttons = {16, 64} },
    { name = "Rashoumon", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
  },
  ["Leona (Orochi)"] = {
    { name = "I-Slasher", motion = {"down", "downback", "back"}, buttons = {16, 64} },
    { name = "Gravity Storm", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Rebel Spark", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Iori (Orochi)"] = {
    { name = "Geshiki: Goufu In \"Shinigame\"", motion = {"forward"}, buttons = {32} },
    { name = "108 Shiki: Yami Barai", motion = {"down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "100 Shiki: Oniyaki", motion = {"forward", "down", "downforward"}, buttons = {16, 64} },
    { name = "212 Shiki: Kototsuki In", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {32, 128} },
    { name = "Kuzukaze", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 64}, close = true },
    { name = "Kin 1211 Shiki: Ya Otome", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Ura 108 Shiki: Ya Sakazuki", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Omega Rugal"] = {
    { name = "Double Tomahawk", motion = {"forward"}, buttons = {32} },
    { name = "Vanishing Rush", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Dark Barrier", motion = {"down", "downforward", "forward"}, buttons = {32, 128} },
    { name = "Genocide Cutter", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Gigantic Pressure", motion = {"down", "downforward", "forward", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64} },
    { name = "Rugal Execution", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Destruction Omega", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
  ["Goenitz"] = {
    { name = "Uranagi", motion = {"forward"}, buttons = {16} },
    { name = "Yonokaze", motion = {"back", "downback", "down", "downforward", "forward"}, buttons = {16, 32, 64, 128} },
    { name = "Wanpyou Tokobuse", motion = {"down", "downback", "back"}, buttons = {16} },
    { name = "Wanpyou Mametsu", motion = {"down", "downback", "back"}, buttons = {64} },
    { name = "Hyouga", motion = {"down", "downback", "back"}, buttons = {32, 128} },
    { name = "Shin Kototsuki Souga", motion = {"forward", "downforward", "down", "downback", "back", "forward"}, buttons = {32, 128} },
    { name = "Yamidoukoku", motion = {"forward", "downforward", "down", "downback", "back", "forward", "downforward", "down", "downback", "back"}, buttons = {16, 64}, close = true },
    { name = "Shin Ya Otome: Mizuchi", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Shin Ya Otome: Jissoukoku", motion = {"down", "downback", "back", "back", "downback", "down", "downforward", "forward"}, buttons = {16, 64} },
  },
  ["Orochi"] = {
    { name = "Harae", motion = {"down", "downforward", "forward"}, buttons = {16} },
    { name = "Tadasu", motion = {"down", "downforward", "forward"}, buttons = {128} },
    { name = "Honosusori", motion = {"forward", "downforward", "down", "downback", "back"}, buttons = {16, 32, 64, 128} },
    { name = "Utsushi Iwai", motion = {"down", "downforward", "forward"}, buttons = {32, 64} },
    { name = "Ukei", motion = {"forward", "down", "downforward"}, buttons = {32, 128} },
    { name = "Oomiwa", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {16, 64} },
    { name = "Marukare", motion = {"down", "downforward", "forward", "down", "downforward", "forward"}, buttons = {32, 128} },
  },
}
return commandSets
